// <auto-generated>
// This code was generated by a kontent-generators-net tool
// (see https://github.com/Kentico/kontent-generators-net).
//
// Changes to this file may cause incorrect behavior and will be lost if the code is regenerated.
// For further modifications of the class, create a separate file with the partial class.
// </auto-generated>

using System;
using System.Collections.Generic;
using Kentico.Kontent.Delivery.Abstractions;

namespace StatiqTutorial
{
    public partial class Testimonial
    {
        public const string Codename = "testimonial";
        public const string AuthorCodename = "author";
        public const string ContentCodename = "content";
        public const string DateCodename = "date";

        public string Author { get; set; }
        public string Content { get; set; }
        public DateTime? Date { get; set; }
        public IContentItemSystemAttributes System { get; set; }
    }
}